import { supabase } from '@/lib/supabase/client';
import { summarizeError, classifySeverity } from '@/lib/hf/pipeline';
import { createGitHubIssue } from '@/lib/github/issues';
import { sendTelegramMessage } from '@/lib/notifications/telegram';

interface ErrorEventInput {
  source: string;
  title: string;
  stackTrace: string;
  projectRepo: string;
  url?: string;
}

const PRIORITY_LABELS = {
  p0: '🔴 P0-CRITICAL',
  p1: '🟡 P1-HIGH',
  p2: '🟢 P2-LOW'
};

export async function processErrorEvent(event: ErrorEventInput) {
  // 1. Deduplicate — don't create duplicate issues for same error in 1 hr
  const oneHourAgo = new Date(Date.now() - 3600000).toISOString();
  const { data: existing } = await supabase
    .from('error_events')
    .select('id')
    .eq('repo', event.projectRepo)
    .ilike('raw_payload->>title', event.title)
    .gt('created_at', oneHourAgo)
    .single();

  if (existing) return; // Already handled

  // 2. Summarize with HuggingFace
  const rawText = `${event.title}\n\n${event.stackTrace}`;
  const summary = await summarizeError(rawText);
  const severity = await classifySeverity(summary);

  // 3. Create GitHub issue
  const issueNumber = await createGitHubIssue({
    repo: event.projectRepo,
    title: `[Nex 🤖] [${severity.toUpperCase()}] ${event.title}`,
    body: buildIssueBody(summary, event, severity),
    labels: ['bug', 'nex-detected', severity],
    assignee: process.env.NEX_OWNER_GITHUB_USERNAME!
  });

  // 4. Store in Supabase
  await supabase.from('error_events').insert({
    source: event.source,
    repo: event.projectRepo,
    severity,
    raw_payload: event,
    nex_summary: summary,
    github_issue_number: issueNumber
  });

  // 5. Notify via Telegram
  const priorityLabel = PRIORITY_LABELS[severity];
  await sendTelegramMessage(
    `${priorityLabel} Error detected in \`${event.projectRepo}\`\n\n` +
    `*Summary:* ${summary}\n\n` +
    `*Source:* ${event.source}\n` +
    `*Issue:* #${issueNumber}`
  );
}

function buildIssueBody(
  summary: string,
  event: ErrorEventInput,
  severity: string
): string {
  return `## 🤖 Nex Error Report

**Severity:** \`${severity.toUpperCase()}\`
**Source:** ${event.source}
**Detected at:** ${new Date().toISOString()}
${event.url ? `**Source URL:** ${event.url}` : ''}

---

## Plain English Summary

${summary}

---

## Raw Error

<details>
<summary>Click to expand stack trace</summary>

\`\`\`
${event.stackTrace}
\`\`\`

</details>

---
*Auto-generated by [Nex[bot]](https://nex.bbuilds.dev) — your DevOps engineer*`;
}